<li><a href="">発表する</a></li>
            <li><a href="">ユーザーを追加する</a></li>
            <li><a href="">コースを追加する</a></li>
            <li><a href="">科目を追加する</a> </li>
            <li><a href="">ユーザーを表示する</a> </li>
            <li><a href="">コースのリストを表示する</a> </li>
            <li><a href="">学生のリストを表示する</a> </li>
            <li><a href="">支払いのリスト</a> </li>
            <li><a href="">バックアップする</a> </li>
            <li><a href="">レストアする</a> </li>